spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://34.116.187.18:5432/postgres
    username: postgres
    password: elomatko1
    driverClassName: org.postgresql.Driver